services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Mail\:
        resource: '%kernel.root_dir%/Mail/*'

    App\Mail\Service\MailSender:
        lazy: true

    App\Mail\Service\HtmlMailSender:
        lazy: true