nelmio_api_doc:
    documentation:
        host: '%rest_api.host%'
        schemes: [https, http]
        info:
            title: Coloc Matching REST API
            version: 2.1.0
        securityDefinitions:
            bearer_token:
                type: apiKey
                description: 'Value: Bearer {jwt}'
                name: Authorization
                in: header
        security:
            -   bearer_token: []
    areas:
        default:
            path_patterns: ["^/rest/"]
        public:
            path_patterns: ["^/rest/(?!admin)"]
        admin:
            path_patterns: ["^/rest/admin"]
        users:
            path_patterns: ["^/rest/users"]
        announcements:
            path_patterns: ["^/rest/announcements"]
        groups:
            path_patterns: ["^/rest/groups"]
        me:
            path_patterns: ["^/rest/me"]
    models:
        use_jms: true
