services:
    coloc_matching.core.user_provider: '@ColocMatching\CoreBundle\Security\User\UserProvider'
    coloc_matching.core.jwt_token_encoder: '@ColocMatching\CoreBundle\Security\User\JwtEncoder'
    coloc_matching.core.form_validator: '@ColocMatching\CoreBundle\Validator\FormValidator'
    coloc_matching.core.user_password_validator: '@ColocMatching\CoreBundle\Validator\Constraint\UserPasswordValidator'
    coloc_matching.core.unique_value_validator: '@ColocMatching\CoreBundle\Validator\Constraint\UniqueValueValidator'
    coloc_matching.core.address_value_validator: '@ColocMatching\CoreBundle\Validator\Constraint\AddressValueValidator'
    coloc_matching.form.type.address_type_to_address_transformer: '@ColocMatching\CoreBundle\Form\DataTransformer\AddressTypeToAddressTransformer'
    coloc_matching.core.event_dispatcher_visitor: '@ColocMatching\CoreBundle\Service\EventDispatcherVisitor'
    coloc_matching.core.mailer: '@ColocMatching\CoreBundle\Service\MailerService'
    coloc_matching.core.password_requester: '@ColocMatching\CoreBundle\Service\PasswordRequester'
    coloc_matching.core.user_status_handler: '@ColocMatching\CoreBundle\Service\UserStatusHandler'
    coloc_matching.core.role: '@ColocMatching\CoreBundle\Service\RoleService'
    coloc_matching.core.update_listener: '@ColocMatching\CoreBundle\Listener\UpdateListener'
    coloc_matching.core.invitation_listener: '@ColocMatching\CoreBundle\Listener\InvitationListener'
    coloc_matching.core.picture_listener: '@ColocMatching\CoreBundle\Listener\PictureListener'
    coloc_matching.core.delete_announcement_event_subscriber: '@ColocMatching\CoreBundle\Listener\DeleteAnnouncementEventSubscriber'
    coloc_matching.core.user_listener: '@ColocMatching\CoreBundle\Listener\UserListener'
    coloc_matching.core.cache_driver_listener: '@ColocMatching\CoreBundle\Listener\CacheDriverListener'
    coloc_matching.core.user_dto_manager: '@ColocMatching\CoreBundle\Manager\User\UserDtoManager'
    coloc_matching.core.announcement_dto_manager: '@ColocMatching\CoreBundle\Manager\Announcement\AnnouncementDtoManager'
    coloc_matching.core.historic_announcement_dto_manager: '@ColocMatching\CoreBundle\Manager\Announcement\HistoricAnnouncementDtoManager'
    coloc_matching.core.group_dto_manager: '@ColocMatching\CoreBundle\Manager\Group\GroupDtoManager'
    coloc_matching.core.visit_dto_manager: '@ColocMatching\CoreBundle\Manager\Visit\VisitDtoManager'
    coloc_matching.core.invitation_dto_manager: '@ColocMatching\CoreBundle\Manager\Invitation\InvitationDtoManager'
    coloc_matching.core.private_conversation_dto_manager: '@ColocMatching\CoreBundle\Manager\Message\PrivateConversationDtoManager'
    coloc_matching.core.user_token_dto_manager: '@ColocMatching\CoreBundle\Manager\User\UserTokenDtoManager'
    coloc_matching.core.group_conversation_dto_manager: '@ColocMatching\CoreBundle\Manager\Message\GroupConversationDtoManager'
    coloc_matching.core.user_dto_mapper: '@ColocMatching\CoreBundle\Mapper\User\UserDtoMapper'
    coloc_matching.core.profile_picture_dto_mapper: '@ColocMatching\CoreBundle\Mapper\User\ProfilePictureDtoMapper'
    coloc_matching.core.profile_dto_mapper: '@ColocMatching\CoreBundle\Mapper\User\ProfileDtoMapper'
    coloc_matching.core.announcement_preference_dto_mapper: '@ColocMatching\CoreBundle\Mapper\User\AnnouncementPreferenceDtoMapper'
    coloc_matching.core.user_preference_dto_mapper: '@ColocMatching\CoreBundle\Mapper\User\UserPreferenceDtoMapper'
    coloc_matching.core.announcement_dto_mapper: '@ColocMatching\CoreBundle\Mapper\Announcement\AnnouncementDtoMapper'
    coloc_matching.core.historic_announcement_dto_mapper: '@ColocMatching\CoreBundle\Mapper\Announcement\HistoricAnnouncementDtoMapper'
    coloc_matching.core.housing_dto_mapper: '@ColocMatching\CoreBundle\Mapper\Announcement\HousingDtoMapper'
    coloc_matching.core.comment_dto_mapper: '@ColocMatching\CoreBundle\Mapper\Announcement\CommentDtoMapper'
    coloc_matching.core.announcement_picture_dto_mapper: '@ColocMatching\CoreBundle\Mapper\Announcement\AnnouncementPictureDtoMapper'
    coloc_matching.core.group_dto_mapper: '@ColocMatching\CoreBundle\Mapper\Group\GroupDtoMapper'
    coloc_matching.core.group_picture_dto_mapper: '@ColocMatching\CoreBundle\Mapper\Group\GroupPictureDtoMapper'
    coloc_matching.core.visit_dto_mapper: '@ColocMatching\CoreBundle\Mapper\Visit\VisitDtoMapper'
    coloc_matching.core.invitation_dto_mapper: '@ColocMatching\CoreBundle\Mapper\Invitation\InvitationDtoMapper'
    coloc_matching.core.private_conversation_dto_mapper: '@ColocMatching\CoreBundle\Mapper\Message\PrivateConversationDtoMapper'
    coloc_matching.core.private_message_dto_mapper: '@ColocMatching\CoreBundle\Mapper\Message\PrivateMessageDtoMapper'
    coloc_matching.core.user_token_dto_mapper: '@ColocMatching\CoreBundle\Mapper\User\UserTokenDtoMapper'
    coloc_matching.core.group_conversation_dto_mapper: '@ColocMatching\CoreBundle\Mapper\Message\GroupConversationDtoMapper'
    coloc_matching.core.group_message_dto_mapper: '@ColocMatching\CoreBundle\Mapper\Message\GroupMessageDtoMapper'
