# Users administration
coloc_matching.rest.admin.user:
    type: annotation
    resource: "@RestBundle/Controller/Rest/v1/Administration/User/UserController.php"


# Historic announcements administration
coloc_matching.rest.admin.announcement.historic:
    type: annotation
    resource: "@RestBundle/Controller/Rest/v1/Administration/Announcement/HistoricAnnouncementController.php"


# Visits administration
coloc_matching.rest.admin.visit:
    type: annotation
    resource: "@RestBundle/Controller/Rest/v1/Administration/Visit/VisitController.php"