# Routing for /announcements
coloc_matching.rest.announcement:
    type: annotation
    resource: ColocMatching\RestBundle\Controller\Rest\v1\Announcement\AnnouncementController


# Routing for /announcements/{id}/pictures
coloc_matching.rest.announcement.picture:
    type: annotation
    resource: ColocMatching\RestBundle\Controller\Rest\v1\Announcement\AnnouncementPictureController


# Routing for /announcements/{id}/housing
coloc_matching.rest.announcement.housing:
    type: annotation
    resource: ColocMatching\RestBundle\Controller\Rest\v1\Announcement\HousingController


# Routing for /announcements/{id}/comments
coloc_matching.rest.announcement.comment:
    type: annotation
    resource: ColocMatching\RestBundle\Controller\Rest\v1\Announcement\AnnouncementCommentController


coloc_matching.rest.announcement.history:
    type: annotation
    resource: "@RestBundle/Controller/Rest/v1/Announcement/HistoricAnnouncementController.php"
