# Routing for /groups
coloc_matching.core.api.group:
    type: annotation
    resource: ColocMatching\RestBundle\Controller\Rest\v1\Group\GroupController


# Routing for /groups/{id}/picture
coloc_matching.core.api.group.picture:
    type: annotation
    resource: ColocMatching\RestBundle\Controller\Rest\v1\Group\GroupPictureController


# Routing for /groups/{id}/visits
coloc_matching.core.api.group.visit:
    type: annotation
    resource: ColocMatching\RestBundle\Controller\Rest\v1\Visit\GroupVisitController


# Routing for /announcements/{id}/invitations
coloc_matching.core.api.announcement.invitation:
    type: annotation
    resource: ColocMatching\RestBundle\Controller\Rest\v1\Invitation\GroupInvitationController
