# Routing for /groups
coloc_matching.rest.group:
    type: annotation
    resource: ColocMatching\RestBundle\Controller\Rest\v1\Group\GroupController


# Routing for /groups/{id}/picture
coloc_matching.rest.group.picture:
    type: annotation
    resource: ColocMatching\RestBundle\Controller\Rest\v1\Group\GroupPictureController
