# Routing for /invitations
coloc_matching.rest.invitation:
    type: annotation
    resource: ColocMatching\RestBundle\Controller\Rest\v1\Invitation\InvitationController


# Routing for /users/{id}/invitations
coloc_matching.rest.invitation.user:
    type: annotation
    resource: ColocMatching\RestBundle\Controller\Rest\v1\Invitation\UserInvitationController


# Routing for /announcements/{id}/invitations
coloc_matching.rest.invitation.announcement:
    type: annotation
    resource: ColocMatching\RestBundle\Controller\Rest\v1\Invitation\AnnouncementInvitationController


# Routing for /groups/{id}/invitations
coloc_matching.rest.invitation.group:
    type: annotation
    resource: ColocMatching\RestBundle\Controller\Rest\v1\Invitation\GroupInvitationController
