# Routing for /users/{id}/visits
coloc_matching.rest.visit.user:
    type: annotation
    resource: ColocMatching\RestBundle\Controller\Rest\v1\Visit\UserVisitController


# Routing for /announcements/{id}/visits
coloc_matching.rest.visit.announcement:
    type: annotation
    resource: ColocMatching\RestBundle\Controller\Rest\v1\Visit\AnnouncementVisitController


# Routing for /groups/{id}/visits
coloc_matching.rest.visit.group:
    type: annotation
    resource: ColocMatching\RestBundle\Controller\Rest\v1\Visit\GroupVisitController
