<?php

namespace Appartoo\CoreBundle\Repository\User;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function findWithPagination(int $offset, int $limit) {
        $queryBuilder = $this->createQueryBuilder('u');
        
        $queryBuilder->setMaxResults($limit)
            ->setFirstResult($offset);
        
        return $queryBuilder->getQuery()->getResult();
    }

    public function countAll() {
        $queryBuilder = $this->createQueryBuilder('u');
        
        $queryBuilder->select('COUNT(u)');
        
        return $queryBuilder->getQuery()->getSingleScalarResult();
    }

}
