services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    ColocMatching\MailBundle\:
        resource: '%kernel.project_dir%/src/ColocMatching/MailBundle/*'


    ColocMatching\MailBundle\Service\MailSender:
        lazy: true

    ColocMatching\MailBundle\Service\HtmlMailSender:
        lazy: true