## Routing for /auth-tokens/
#coloc_matching.rest.authentication:
#    type: annotation
#    resource: "@RestBundle/Controller/Rest/v1/AuthenticationController.php"
#
#
## Routing for /registrations
#coloc_matching.rest.registration:
#    type: annotation
#    resource: "@RestBundle/Controller/Rest/v1/User/RegistrationController.php"
#
#
## Routing for /password
#coloc_matching.rest.password:
#    type: annotation
#    resource: "@RestBundle/Controller/Rest/v1/User/RequestPasswordController.php"
#
#
## Routing for all resources on users
#coloc_matching.rest.user:
#    resource: "@RestBundle/Resources/config/routing/user_routing.yml"
#
#
## Routing for all resources on announcements
#coloc_matching.rest.announcement:
#    resource: "@RestBundle/Resources/config/routing/announcement_routing.yml"
#
#
## Routing for all resources on groups
#coloc_matching.rest.group:
#    resource: "@RestBundle/Resources/config/routing/group_routing.yml"
#
#
## Routing for all resources on invitations
#coloc_matching.rest.invitation:
#    resource: "@RestBundle/Resources/config/routing/invitation_routing.yml"
#
#
## Routing for all resources on conversations
#coloc_matching.rest.conversation:
#    resource: "@RestBundle/Resources/config/routing/conversation_routing.yml"
#
#
## Routing for all visits
#coloc_matching.rest.visits:
#    resource: "@RestBundle/Resources/config/routing/visit_routing.yml"
#
#
## Routing for /administration
#coloc_matching.rest.administration:
#    prefix: /admin
#    resource: "@RestBundle/Resources/config/routing/administration_routing.yml"
