services:
    # ------------------------------  Voters  ------------------------------
    coloc_matching.rest.announcement_voter:
        class: ColocMatching\RestBundle\Security\Authorization\Voter\AnnouncementVoter
        arguments:
            - "@logger"
            - "@coloc_matching.core.announcement_dto_manager"
        tags:
            - { name: "security.voter" }


    coloc_matching.rest.group_voter:
        class: ColocMatching\RestBundle\Security\Authorization\Voter\GroupVoter
        arguments:
            - "@logger"
            - "@coloc_matching.core.group_dto_manager"
        tags:
            - { name: "security.voter" }


    coloc_matching.rest.visit_voter:
        class: ColocMatching\RestBundle\Security\Authorization\Voter\VisitVoter
        arguments: ["@logger"]
        tags:
            - { name: "security.voter" }


    coloc_matching.rest.invitation_voter:
        class: ColocMatching\RestBundle\Security\Authorization\Voter\InvitationVoter
        arguments: ["@logger"]
        tags:
            - { name: "security.voter" }


    coloc_matching.rest.historic_announcement_voter:
        class: ColocMatching\RestBundle\Security\Authorization\Voter\HistoricAnnouncementVoter
        arguments:
            - "@logger"
            - "@coloc_matching.core.role"
        tags:
            - { name: "security.voter" }


    # ------------------------------  Others  ------------------------------
    coloc_matching.rest.user_authentication_handler:
        class: ColocMatching\RestBundle\Security\UserAuthenticationHandler
        arguments:
          - "@logger"
          - "@coloc_matching.core.user_dto_manager"
          - "@coloc_matching.core.user_dto_mapper"
          - "@coloc_matching.core.form_validator"
          - "@security.password_encoder"
